### ISSUE TITLE
Wireguard VPN Issue

### ISSUE THREAD

**Issue by galaxyrun** [HarvsG/ha-glinet4-integration#11]
I am using a GLinet Flint Router with a WireGuard client running on it. However, the integration does not effectively control the VPN. Ideally, I should be able to toggle it on and off, but this functionality is not working as expected.

Interestingly, when I activate the VPN through the router, I can then deactivate it using Home Assistant. The Home Assistant switch briefly toggles off, but then shortly after shows that the VPN is still on, even though it should be off. 

After this, I am unable to control the switch anymore. Only when I activate the VPN again through the router, I can once again deactivate it using Home Assistant.

Home Assistant
```
Core 2024.3.0
Supervisor 2024.03.0
Operating System 12.1
Frontend 20240306.0
```
Router
```
Hostname GL-AX1800
Model GL Technologies, Inc. AX1800
Architecture ARMv7 Processor rev 4 (v7l)
OpenWrt Version OpenWrt 21.02-SNAPSHOT r16399+165-c67509efd7
Kernel Version 4.4.60
```

**Comment by HarvsG** [comment]
Fixed in the latest version
It is still very slow to update the state of the switch after turning it on - about a minute
